Assets/Project/JaeYoonOh.meta
Assets/Project/JaeYoonOh/New Scene.unity
Assets/Project/JaeYoonOh/New Scene.unity.meta
ProjectSettings/SceneTemplateSettings.json

JaeYoonOh 커밋 테스트

---

Assets/Project/ParkJunMin.meta
Assets/Project/ParkJunMin/Materials.meta
Assets/Project/ParkJunMin/Materials/Ground.mat
Assets/Project/ParkJunMin/Materials/Ground.mat.meta
Assets/Project/ParkJunMin/Materials/PlayerMaterial.mat
Assets/Project/ParkJunMin/Materials/PlayerMaterial.mat.meta
Assets/Project/ParkJunMin/Scene.meta
Assets/Project/ParkJunMin/Scene/TestScene.unity
Assets/Project/ParkJunMin/Scene/TestScene.unity.meta
Assets/Project/ParkJunMin/Scripts.meta
Assets/Project/ParkJunMin/Scripts/BaseState.cs
Assets/Project/ParkJunMin/Scripts/BaseState.cs.meta
Assets/Project/ParkJunMin/Scripts/PlayerController.cs
Assets/Project/ParkJunMin/Scripts/PlayerController.cs.meta
ProjectSettings/SceneTemplateSettings.json
ProjectSettings/TagManager.asset

Commit Test

---

Assets/Project/YeonSeung.meta
Assets/Project/YeonSeung/00Scene.meta
Assets/Project/YeonSeung/01Materials.meta
Assets/Project/YeonSeung/01Materials/TestMaterial.mat
Assets/Project/YeonSeung/01Materials/TestMaterial.mat.meta
Assets/Project/YeonSeung/02Scripts.meta
Assets/Project/YeonSeung/03Animations.meta
Assets/Project/YeonSeung/04Sprites.meta
Assets/Project/YeonSeung/05Prefabs.meta

[chore] TestMaterial 추가

---

Assets/Project/KimEusung/Scenes.meta
Assets/Project/KimEusung/Scenes/KimEusungTesterSin.unity
Assets/Project/KimEusung/Scenes/KimEusungTesterSin.unity.meta
Assets/Project/KimEusung/Scripts.meta
Assets/Project/KimEusung/Scripts/PlayerMover.cs
Assets/Project/KimEusung/Scripts/PlayerMover.cs.meta
ProjectSettings/TagManager.asset

[Update] 움직임 점프구현

---

Assets/Project/YeonSeung/00Scene/TestingScene.unity
Assets/Project/YeonSeung/02Scripts/DustEffect.cs
Assets/Project/YeonSeung/02Scripts/DustEffect.cs.meta
Assets/Project/YeonSeung/02Scripts/PlayerTester.cs
Assets/Project/YeonSeung/02Scripts/PlayerTester.cs.meta
Assets/Project/YeonSeung/05Prefabs/DustEffect.prefab
Assets/Project/YeonSeung/05Prefabs/DustEffect.prefab.meta
Assets/Project/YeonSeung/05Prefabs/UIManager.prefab
Assets/Project/YeonSeung/05Prefabs/UIManager.prefab.meta

[Feat] DustEffect 추가

---

Assets/Project/ParkJunMin/Scene/TestScene.unity
Assets/Project/ParkJunMin/Scripts/PlayerController.cs
Assets/Project/ParkJunMin/Scripts/States/FallState.cs
Assets/Project/ParkJunMin/Scripts/States/JumpState.cs
Assets/Project/Public/Prefabs/Player/PlayerPrefab.prefab
Assets/Project/Public/Prefabs/Player/PlayerPrefab.prefab.meta

- 공중상태의 이동속도와 max이동속도는 기존 땅에서의 이동속도에 offset값을 곱해서 정해짐
- 공중상태의 이동속도를 변경하지 않아도 자동으로 적용됨

feat : 플레이어 공중 상태 이동 추가

---

Assets/Project/KimEusung/New Material.mat
Assets/Project/KimEusung/New Material.mat.meta

[restoration]복구함

---

Assets/Project/ParkJunMin/Scripts/PlayerController.cs
Assets/Project/ParkJunMin/Scripts/PlayerModel.cs
Assets/Project/ParkJunMin/Scripts/PlayerView.cs
Assets/Project/ParkJunMin/Scripts/States/DamagedState.cs
Assets/Project/ParkJunMin/Scripts/States/DamagedState.cs.meta
Assets/Project/ParkJunMin/Scripts/States/DeadState.cs
Assets/Project/ParkJunMin/Scripts/States/IdleState.cs
Assets/Project/ParkJunMin/Scripts/States/RunState.cs

keycode.O : 피격 트리거
keycode.P : 죽음 트리거

Feat: 플레이어 피격 상태 추가, 임시 트리거 추가

---

Assets/Project/KimEusung/Animations/PlayerAnimations/PlayerMovingAnimation.controller
Assets/Project/KimEusung/Animations/PlayerAnimations/fall_Blue.anim
Assets/Project/KimEusung/Animations/PlayerAnimations/fall_Red.anim

[Fix] 컨벤션 이름변경 픽스

---

Assets/Project/KimEusung/Animations/PlayerAnimations/PlayerMovingAnimation.controller
Assets/Project/ParkJunMin/Prefabs/PlayerTemp.prefab
Assets/Project/ParkJunMin/Scene/TestScene.unity
Assets/Project/ParkJunMin/Scripts/PlayerController.cs
Assets/Project/ParkJunMin/Scripts/PlayerView.cs
Assets/Project/ParkJunMin/Scripts/States/DamagedState.cs
Assets/Project/ParkJunMin/Scripts/States/DeadState.cs
Assets/Project/ParkJunMin/Scripts/States/DoubleJumpState.cs
Assets/Project/ParkJunMin/Scripts/States/FallState.cs
Assets/Project/ParkJunMin/Scripts/States/IdleState.cs
Assets/Project/ParkJunMin/Scripts/States/JumpState.cs
Assets/Project/ParkJunMin/Scripts/States/RunState.cs
Assets/Project/ParkJunMin/Scripts/States/SpawnState.cs
Assets/Project/ParkJunMin/Scripts/States/WakeupState.cs
Assets/Project/ParkJunMin/Scripts/States/WakeupState.cs.meta
Assets/Project/Public/Prefabs/Player/PlayerTemp.prefab

플레이어 피격, 죽음 및 리스폰 상태 구현

---

Assets/Project/KimEusung/Animations/PlayerAnimations/PlayerMovingAnimation.controller
Assets/Project/KimEusung/Map.meta
Assets/Project/KimEusung/Map/MapPrefabs.prefab
Assets/Project/KimEusung/Map/MapPrefabs.prefab.meta
Assets/Project/KimEusung/Map/MapRenderTexture.renderTexture
Assets/Project/KimEusung/Map/MapRenderTexture.renderTexture.meta
Assets/Project/KimEusung/Scenes/TestrMap.unity
Assets/Project/KimEusung/Scenes/TestrMap.unity.meta
Assets/Project/KimEusung/Scripts/Map.cs
Assets/Project/KimEusung/Scripts/Map.cs.meta

- M키를 누르면 지도가 나오고 다시 누르면 지도가 꺼짐
- 플레이어 오브젝트에 움직임 기타등등 관련 관련된 스크립트를 넣어줘야함

[Feat] : 지도 구현

---

Assets/Project/ParkJunMin/Scripts/PlayerController.cs

chore : wallCheckRoutine 작성중

---

Assets/Project/ParkJunMin/Scene/TestScene.unity
Assets/Project/ParkJunMin/Scripts/PlayerController.cs
Assets/Project/ParkJunMin/Scripts/PlayerView.cs
Assets/Project/ParkJunMin/Scripts/States/DoubleJumpState.cs
Assets/Project/ParkJunMin/Scripts/States/SpawnState.cs
Assets/Project/Public/Prefabs/Player/PlayerBeforeTasking.prefab
Assets/Project/Public/Prefabs/Player/PlayerBeforeTasking.prefab.meta

GroundCheck 리팩토링 및 WallCheck 루틴 생성

Feat : 벽타기 구현 전 준비작업

---

Assets/Project/KimEusung/Sprites/RedPlayer/WallClimbing/WallGrabStart/fire Spirit Wall Climbing1.png.meta
Assets/Project/KimEusung/Sprites/RedPlayer/WallClimbing/WallGrabStart/fire Spirit Wall Climbing2.png.meta
Assets/Project/KimEusung/Sprites/RedPlayer/WallClimbing/WallGrabStart/fire Spirit Wall Climbing3.png.meta
Assets/Project/KimEusung/Sprites/RedPlayer/WallClimbing/WallGrabStart/fire Spirit Wall Climbing4.png.meta
Assets/Project/KimEusung/Sprites/RedPlayer/WallClimbing/WallGrabStart/fire Spirit Wall Climbing5.png.meta
Assets/Project/KimEusung/Sprites/RedPlayer/WallClimbing/WallGrabStart/fire Spirit Wall Climbing6.png.meta
Assets/Project/KimEusung/Sprites/RedPlayer/WallClimbing/WallJump/wall jump1.png.meta
Assets/Project/KimEusung/Sprites/RedPlayer/WallClimbing/WallJump/wall jump2.png.meta
Assets/Project/KimEusung/Sprites/RedPlayer/WallClimbing/WallJump/wall jump3.png.meta
Assets/Project/KimEusung/Sprites/RedPlayer/WallClimbing/WallJump/wall jump4.png.meta
Assets/Project/KimEusung/Sprites/RedPlayer/WallClimbing/WallJump/wall jump5.png.meta
Assets/Project/KimEusung/Sprites/RedPlayer/WallClimbing/WallJump/wall jump6.png.meta
Assets/Project/KimEusung/Sprites/RedPlayer/WallClimbing/WallJump/wall jump7.png.meta
Assets/Project/KimEusung/Sprites/RedPlayer/WallClimbing/WallSliding/fire Spirit Wall Climbing10.png.meta
Assets/Project/KimEusung/Sprites/RedPlayer/WallClimbing/WallSliding/fire Spirit Wall Climbing7.png.meta
Assets/Project/KimEusung/Sprites/RedPlayer/WallClimbing/WallSliding/fire Spirit Wall Climbing8.png.meta
Assets/Project/KimEusung/Sprites/RedPlayer/WallClimbing/WallSliding/fire Spirit Wall Climbing9.png.meta

[Fix] 벽 애니메이션 수정중(정기머지)

---

Assets/Project/ParkJunMin/Scene/TestScene.unity
Assets/Project/ParkJunMin/Scripts/PartialPlayerController.cs
Assets/Project/ParkJunMin/Scripts/PlayerController.cs
Assets/Project/ParkJunMin/Scripts/States/Wall/WallJumpState.cs

WallCheck 및 WallJump Power 값 조정중입니다

chore : WallJump 조정중

---

Assets/Project/KimEusung/Scenes/TestrMap.unity
Assets/Project/KimEusung/Sprites/BluePlayer/WallClimbing/WallGrabStart/Water Spirit Wall Climbing1.png.meta
Assets/Project/KimEusung/Sprites/BluePlayer/WallClimbing/WallGrabStart/Water Spirit Wall Climbing2.png.meta
Assets/Project/KimEusung/Sprites/BluePlayer/WallClimbing/WallGrabStart/Water Spirit Wall Climbing3.png.meta
Assets/Project/KimEusung/Sprites/BluePlayer/WallClimbing/WallGrabStart/Water Spirit Wall Climbing4.png.meta
Assets/Project/KimEusung/Sprites/BluePlayer/WallClimbing/WallGrabStart/Water Spirit Wall Climbing5.png.meta
Assets/Project/KimEusung/Sprites/BluePlayer/WallClimbing/WallGrabStart/Water Spirit Wall Climbing6.png.meta
Assets/Project/KimEusung/Sprites/BluePlayer/WallClimbing/WallJump/water_wall jump1.png.meta
Assets/Project/KimEusung/Sprites/BluePlayer/WallClimbing/WallJump/water_wall jump2.png.meta
Assets/Project/KimEusung/Sprites/BluePlayer/WallClimbing/WallJump/water_wall jump3.png.meta
Assets/Project/KimEusung/Sprites/BluePlayer/WallClimbing/WallJump/water_wall jump4.png.meta
Assets/Project/KimEusung/Sprites/BluePlayer/WallClimbing/WallJump/water_wall jump5.png.meta
Assets/Project/KimEusung/Sprites/BluePlayer/WallClimbing/WallJump/water_wall jump6.png.meta
Assets/Project/KimEusung/Sprites/BluePlayer/WallClimbing/WallJump/water_wall jump7.png.meta
Assets/Project/KimEusung/Sprites/BluePlayer/WallClimbing/WallSliding/Water Spirit Wall Climbing10.png.meta
Assets/Project/KimEusung/Sprites/BluePlayer/WallClimbing/WallSliding/Water Spirit Wall Climbing7.png.meta
Assets/Project/KimEusung/Sprites/BluePlayer/WallClimbing/WallSliding/Water Spirit Wall Climbing8.png.meta
Assets/Project/KimEusung/Sprites/BluePlayer/WallClimbing/WallSliding/Water Spirit Wall Climbing9.png.meta
Assets/Project/KimEusung/Sprites/RedPlayer/WallClimbing/WallJump/wall jump7.png.meta

[fix] 플레이어 콜라이더 벽 애니메이션 수정

---

Assets/Project/ParkJunMin/Prefabs/PlayerTemp.prefab
Assets/Project/ParkJunMin/Scene/WallJumpTest.unity
Assets/Project/ParkJunMin/Scripts/PlayerController.cs
Assets/Project/ParkJunMin/Scripts/PlayerView.cs
Assets/Project/ParkJunMin/Scripts/States/InAir/FallState.cs
Assets/Project/ParkJunMin/Scripts/States/Wall/WallJumpState.cs
Assets/Project/Public/Prefabs/Player/PlayerTemp.prefab
Assets/Project/Public/Prefabs/Player/PlayerTemp.prefab.meta

벽에서 튀어나온 뒤 한번 점프가 가능하게 만들어, 튀어나온 방향대로 이동할지 다시 벽으로 돌아갈지 플레이어가 선택할 수 있다
머지 오류로 인해 다시 리퀘스트 합니다

Feat : 벽감지 및 벽점프 로직 수정 + 플레이어 프리팹 갱신

---

Assets/Project/NoSeungJu/Scenes/Develop.unity
Assets/Project/NoSeungJu/Scenes/UIDevelop.unity
Assets/Project/NoSeungJu/Script/DarkArea.cs
Assets/Project/NoSeungJu/Script/Trap/Trap.cs
Assets/Project/ParkJunMin/Materials/New Physics Material 2D.physicsMaterial2D
Assets/Project/ParkJunMin/Materials/New Physics Material 2D.physicsMaterial2D.meta
Assets/Project/ParkJunMin/Scene/TagTestScene.unity
Assets/Project/ParkJunMin/Scene/TagTestScene.unity.meta
Assets/Project/ParkJunMin/Scripts/PlayerController.cs
Assets/Project/ParkJunMin/Scripts/States/Basic/IdleState.cs
Assets/Project/Public/Prefabs/Platform/Blue Move Platform.prefab
Assets/Project/Public/Prefabs/Platform/Blue Move Platform.prefab.meta
Assets/Project/Public/Prefabs/Platform/Red Move Platform.prefab
Assets/Project/Public/Prefabs/Platform/Red Move Platform.prefab.meta
Assets/Project/Public/Scripts/Platform/BreakPlatform.cs
Assets/Project/Public/Scripts/Platform/NaturePlatform.cs
Assets/TextMesh Pro/Examples & Extras/Scripts/TMP_TextEventHandler.cs
Assets/TextMesh Pro/Examples & Extras/Scripts/VertexColorCycler.cs

Develop -> TESTMAP

---

Assets/Project/KimEusung/Scenes/TestrMap.unity
Assets/Project/KimEusung/Scripts/Save/GameData.cs
Assets/Project/KimEusung/Scripts/Save/SaveManager.cs

- 3분마다 자동저장 기능을 구현함
- 플레이어 컨트롤러의 hp와 트렌스폼 위치정보를 가져와 저장방식으로 변경

[Feat] 자동저장 기능구현

---

Assets/Project/YeonSeung/00Scene/TestingScene.unity
Assets/Project/YeonSeung/02Scripts/GrassController.cs
Assets/Project/YeonSeung/02Scripts/ParticleManager.cs
Assets/Project/YeonSeung/05Prefabs/ParticleFX/DoubleJumpFX.prefab
Assets/Project/YeonSeung/05Prefabs/ParticleFX/JumpDustFX.prefab
Assets/Project/YeonSeung/05Prefabs/ParticleFX/SmallDustFX.prefab
ProjectSettings/Physics2DSettings.asset

* 파티클매니저 플레이어 하에서 정상작동 확인
* 발판 버전2 마무리

Dev <- YSC241030 머지

---

Assets/Project/PSH/soohyun.unity
Assets/Project/YeonSeung/02Scripts/PrefabColliderRemover.cs
Assets/Project/YeonSeung/02Scripts/PrefabColliderRemover.cs.meta
Assets/Project/YeonSeung/05Prefabs/BoudaryColliders.meta
Assets/Project/YeonSeung/05Prefabs/BoudaryColliders/DShape.prefab
Assets/Project/YeonSeung/05Prefabs/BoudaryColliders/DShape.prefab.meta
Assets/Project/YeonSeung/05Prefabs/BoudaryColliders/LShape.prefab
Assets/Project/YeonSeung/05Prefabs/BoudaryColliders/LShape.prefab.meta
ProjectSettings/Physics2DSettings.asset

맵 콜라이더 수정 1스테이지 완료 
2스테이지 반정도 완료 
일단 머지합니다

Develop <-- YeonSeung241031

---

Assets/Project/KimGyeongya/3Stage.unity.meta

Create : 3스테이지 맵 배치, 1스테이지 출구 벽 오브젝트 삭제

Create : 3스테이지 맵 배치, 1스테이지 출구 벽 오브젝트 삭제

---

Assets/Project/ParkJunMin/Scene/SlopeTest.unity
Assets/Project/ParkJunMin/Scripts/PlayerController.cs
Assets/Project/ParkJunMin/Scripts/PlayerModel.cs
Assets/Project/ParkJunMin/Scripts/States/Basic/DashState.cs
Assets/Project/ParkJunMin/Scripts/States/Basic/RunState.cs
Assets/Project/ParkJunMin/Scripts/States/InAir/DoubleJumpState.cs
Assets/Project/ParkJunMin/Scripts/States/InAir/JumpState.cs
Assets/Project/ParkJunMin/Scripts/States/PlayerState.cs
Assets/Project/ParkJunMin/Scripts/States/Wall/WallGrabState.cs
Assets/Project/Public/Prefabs/Player/Player.prefab

- Alpha1 : 태그 해금
- Alpha2 : 대시 해금
- Alpha3 : 벽점프 해금
- Alpha4 : 더블점프 해금
```c#
// PlayerModel 에 구현됨
public event Action<Ability> OnAbilityUnlocked;
public void UnlockAbilityEvent(Ability _newAbility)
{
OnAbilityUnlocked?.Invoke(_newAbility);
}
```
```c#
public class AbilityUnlockItem : MonoBehaviour
{
public PlayerModel.Ability abilityToUnlock;
private PlayerController player; // PlayerController를 캐싱
private void OnTriggerEnter2D(Collider2D other)
{
// 플레이어와의 충돌을 확인
if (other.CompareTag("Player"))
{
// 플레이어를 따로 등록하는 로직이 없었다면 사용
if (player == null)
{
player = other.GetComponent<PlayerController>();
}
// 능력 해금 메서드를 호출
if (!player.HasAbility(abilityToUnlock)) // 이미 해금된 능력인지 확인
{
player.UnlockAbility(abilityToUnlock); // 능력 해금
player.UnlockAbilityEvent(abilityToUnlock); // 이벤트 호출
} …
```

feat : 플레이어 능력 해금 구현 및 플레이어 프리팹 갱신, 능력 해금 오브젝트 코드 예시 추가

---

Assets/Project/KimEusung/Scenes/TestrMap.unity
Assets/Project/Public/Prefabs/Map/MapPrefabs.prefab
Assets/Project/Public/Scripts/Map/Map.cs
Assets/Project/Public/Scripts/Map/MapAnimation.cs
Assets/Project/Public/Scripts/Map/MapAnimation.cs.meta

[Feat] : 지도 구현 완료

---

Assets/Project/KimEusung/Scenes/TestrMap.unity
Assets/Project/Public/Prefabs/Map/MapPrefabs.prefab
Assets/Project/Public/Scripts/Map/Map.cs

색상변경및 코드 깔끔하게 변경
프리팹 인스펙터창에서 자동드래그되게함

[fix] 지도 색상 변경이 되지않는 문제점 발견 해결함

---

Assets/Project/PSH/0Stage.unity
Assets/Project/PSH/2Stage.unity
Assets/Project/PSH/4Stage.unity

Test psh : 머지

---

Assets/Project/NoSeungJu/Scenes/UIDevelop.unity
Assets/Project/Public/Prefabs/Scene/SceneTrigger.prefab
Assets/Project/Public/Prefabs/Warp/WarpPoint.prefab
Assets/Project/Public/Scenes/Sample/TestStage/TestStage1.unity
Assets/Project/Public/Scenes/Sample/TestStage/TestStage2.unity
Assets/Project/Public/Scenes/Sample/TestStage/TestStage3.unity
Assets/Project/Public/Scenes/Sample/TestStage/TestStage4.unity
Assets/Project/Public/Scripts/Scene/SceneChanger.cs
Assets/Project/Public/Scripts/Scene/SceneLoadTrigger.cs
Assets/Project/Public/Scripts/Scene/TestSceneChanger.cs
Assets/Project/YeoKanghyeok/Scripts/Warp/ButtonController.cs
Assets/Project/YeoKanghyeok/Scripts/Warp/PointController.cs
ProjectSettings/TagManager.asset

언로드 방식을 바꿈, 인스펙터에서 로드씬만 설정해도 됨

Refactor : 씬체인저, 씬트리거 리팩토링

---

Assets/Project/ParkJunMin/Scripts/PlayerController.cs
Assets/Project/ParkJunMin/Scripts/States/Basic/IdleState.cs
Assets/Project/ParkJunMin/Scripts/States/InAir/LandState.cs

리팩토링 및 구현 완료했습니다
사용해보시고 적성 점프 버퍼 타임 설정 및 QA 부탁드립니다

feat : 점프 버퍼 구현

---

Assets/Project/ParkJunMin/Scene/SlopeTest.unity
Assets/Project/ParkJunMin/Scripts/States/Basic/DashState.cs
Assets/Project/ParkJunMin/Scripts/States/Basic/IdleState.cs
Assets/Project/ParkJunMin/Scripts/States/Basic/RunState.cs
Assets/Project/ParkJunMin/Scripts/States/InAir/FallState.cs

refactor : fall 상태전환 변경

---

Assets/Project/KimEusung/Scenes/TestrMap.unity
Assets/Project/Public/Prefabs/Map/MapPrefabs.prefab
Assets/Project/Public/Scripts/Map/Map.cs
Assets/Project/Public/Scripts/Save/GameData.cs
Assets/Project/Public/Scripts/Save/SaveManager.cs

[fix] 지도와 저장기능 수정

---

Assets/Project/Public/Prefabs/Item/Skill/SkillUI/DashTootipUI.prefab
Assets/Project/Public/Prefabs/Item/Skill/SkillUI/DoubleJumpTootipUI.prefab
Assets/Project/Public/Prefabs/Item/Skill/SkillUI/TagTootipUI.prefab
Assets/Project/Public/Prefabs/Item/Skill/SkillUI/WallJumpTootipUI.prefab

Feat : 스킬 구슬 설명 추가

---

Assets/Project/YeonSeung/02Scripts/ParticleManager.cs
Assets/Project/YeonSeung/02Scripts/SoundDataYSC.cs

Dev <- Yeon seung241105

---

Assets/Project/YeonSeung/05Prefabs/ParticleFX/PlatformBLUEFX.prefab
Assets/Project/YeonSeung/05Prefabs/ParticleFX/PlatformBLUEFX.prefab.meta
Assets/Project/YeonSeung/05Prefabs/ParticleFX/PlatformREDFX.prefab
Assets/Project/YeonSeung/05Prefabs/ParticleFX/PlatformREDFX.prefab.meta

[Feat] 뚫는벽 오로라 생성
